# Generated by Django 5.1.3 on 2024-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(blank=True, choices=[('nebulosa', 'Nebulosa'), ('estrela', 'Estrela'), ('galáxia', 'Galáxia'), ('planeta', 'Planeta')], default='', max_length=100, null=True),
        ),
    ]
