# Generated by Django 5.1.3 on 2024-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_foto',
            new_name='data_fotografia',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
